# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'XQArchiveProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for XQArchiveProject

pod 'XQProjectTool', :path => '/Users/wangxingqian/Desktop/XQWorkProject/Tool/XQProjectTool'

end
